name: course_system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - asgiref==3.10.0
      - django==5.2.7
      - django-cors-headers==4.9.0
      - djangorestframework==3.16.1
      - sqlparse==0.5.3
